# Generated by Django 3.0 on 2022-03-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Passsword1', models.CharField(max_length=100)),
                ('Passsword2', models.CharField(max_length=100)),
            ],
        ),
    ]
